# Development Dockerfile
FROM node:20-alpine

WORKDIR /app

# Install dependencies for development
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat openssl

# Enable pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

# Generate Prisma Client inside the container (Alpine => linux-musl)
RUN pnpm prisma generate

# Next.js telemetry disable
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["pnpm", "dev"]
